language: java
sudo: false
install: true

script:
  - mvn clean test


mvn sonar:sonar \
  -Dsonar.projectKey=AssayeAssefa_SonarTest \
  -Dsonar.organization=assayeassefa-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=b5ca1c306e75bc3bb1d127693636b7fb44be67c5
